package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.45

import (
	"backend-service/internal/infrastructure/api/graph/model"
	"context"
	"fmt"
)

// CreateUser is the resolver for the createUser field.
func (r *mutationResolver) CreateUser(ctx context.Context, input model.NewUser) (*model.User, error) {
	panic(fmt.Errorf("not implemented: CreateUser - createUser"))
}

// UserByID is the resolver for the userById field.
// Maps domain entity → GraphQL model so the domain stays free of transport concerns.
func (r *queryResolver) UserByID(ctx context.Context, id string) (*model.User, error) {
	domainUser, err := r.App.GetUserByID.Execute(ctx, id)
	if err != nil {
		return nil, err
	}
	if domainUser == nil {
		return nil, nil
	}

	// Mapper: domain entity → GraphQL transport model
	return &model.User{
		ID:   domainUser.ID,
		Name: domainUser.Name,
	}, nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
